name: Ben MacDougall - Composer
favicon: null
layout_spectrum: 0.19217950850725174
typography_spectrum: 0.31799
title: Ben MacDougall - Composer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaf9fe'
    - '#091136'
    - '#01eefe'
    - '#2b8699'
    - '#fea53d'
  brandStrength: 0.4451968469657004
  lightness: 0.14865192538127303
  saturation: 0.5
  rhythmicContrast: 0.19752738112583756
purpose: []
